### ISSUE TITLE
Add code for Linked Lists

### ISSUE THREAD

**Issue by aman-earthian** [aman-earthian/Data_Structures_and_Algorithms#1]
Add codes for all the basic operations performed on the linked list. Operations of all types of linked list can be added.

**Comment by sanju6890** [comment]
Hi @aman-earthian I want to contribute C++ programs on basic operations on **Linked lists**.
Kindly confirm and assign this issue to me :)

**Comment by aman-earthian** [comment]
Hi @sanju6890, you are most welcome to contribute to this repository but please commit properly indended and clean code that's it.
For any help you can refer to this article:
https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by sanju6890** [comment]
Thanks @aman-earthian 
I have created the pull request for the same (Linked lists).
Kindly review it and merge it, if you find it worth :)

**Comment by manavbhikadiya** [comment]
i would love to do this. please assign this to me.

**Comment by manavbhikadiya** [comment]
@aman-earthian please add code to the main branch.

**Comment by namrata18s** [comment]
I have added circular linked list operations, pls. review it and accept my pull request and merge it.

**Comment by manavbhikadiya** [comment]
i have already added solution of linked list  please  accept my pull request  and merge it..

**Comment by namrata18s** [comment]
@aman-earthian I have created operations on circular linked list which was not created earlier, please review my PR .

**Comment by sayalitandel** [comment]
Hey! @aman-earthian I would love to work on this. Could you please assign it to me?
